var x, y ,z;
x= 8;
y= 5;
z= x-y;
document.write('Subtract of '+ y + ' from '+ x + ' is ' +z);
z= x*y;
document.write('<br>Multiplication of ' + x + ' and ' + y + ' is '+ z);
z=x/y;
document.write('<br>Divide '+ x + ' by '+y+ ' is '+ z);
z=x%y;
document.write('<br>Modulus of '+x +' and '+y+ ' is '+ z);